name: Build and Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'           
      - '.github/workflows/backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies with cache
        uses: bahmutov/npm-install@v1  # Installs Node.js dependencies and caches them automatically to speed up future builds
        with:
          working-directory: ./backend

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_CHATAPP_BACKEND }}
