name: Build and Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'           
      - '.github/workflows/backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies with cache
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./backend

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Database Migrations
        run: npm run migrate:deploy

      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_CHATAPP_BACKEND }}
