name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # No build step here due to routing problem

      - name: Trigger Render frontend deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_CHATAPP }}
